### ISSUE TITLE
Replace plyr functions

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/mortality_bci#105]
There are several call's to `plyr::ldply` --->  to miminise package overhead, it would be nice to replace these with `dplyr` functions if possible.

Here's a tentaive replacement:

```
# Written to work like plyr::ldply
# assumed named list
# does not work with all results below
list_to_df <- function(listfordf, .id='id'){
  df <- cbind(
              names(listfordf),
              lapply(listfordf, as.data.frame) %>% bind_rows())
  names(df)[1] <- .id
  df
}
```

Alas, doesn't work properly yet.

**Comment by jscamac** [comment]
I'm pretty sure I've removed all these plyr calls.
